name: Fault
dependencies:
  - pip=10.0.1=py35_0
  - python=3.5.6
  - setuptools=40.2.0=py35_0
  - wheel=0.31.1=py35_0
  - pip:
    - absl-py==0.2.2
    - astor==0.6.2
    - backcall==0.1.0
    - bleach==1.5.0
    - chardet==3.0.4
    - click==6.7
    - cloudpickle==0.5.3
    - colorama==0.4.1
    - cycler==0.10.0
    - cython==0.28.3
    - dask==0.18.0
    - datashape==0.5.2
    - decorator==4.3.0
    - dicom==0.9.9.post1
    - entrypoints==0.2.3
    - enum34==1.1.6
    - flask==1.0.2
    - future==0.16.0
    - gast==0.2.0
    - grpcio==1.12.1
    - h5py==2.8.0
    - html5lib==0.9999999
    - hyperas==0.4
    - hyperopt==0.1
    - idna==2.7
    - imageio==2.4.1
    - ipykernel==4.8.2
    - ipython==6.4.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.2.1
    - itsdangerous==0.24
    - jedi==0.12.0
    - jinja2==2.10
    - joblib==0.13.0
    - jsonschema==2.6.0
    - jupyter==1.0.0
    - jupyter-client==5.2.3
    - jupyter-console==5.2.0
    - jupyter-core==4.4.0
    - keract==2.5.4
    - keras==2.2.4
    - kiwisolver==1.0.1
    - llvmlite==0.26.0
    - markdown==2.6.11
    - markupsafe==1.0
    - matplotlib==2.2.2
    - mistune==0.8.3
    - mpld3==0.3
    - multipledispatch==0.5.0
    - nbconvert==5.3.1
    - nbformat==4.4.0
    - networkx==1.11
    - nose==1.3.7
    - notebook==5.5.0
    - numba==0.41.0
    - numpy==1.14.5
    - opencv-python==3.4.4.19
    - palettable==3.1.1
    - pandas==0.23.1
    - pandocfilters==1.4.2
    - parso==0.2.1
    - pexpect==4.6.0
    - pickleshare==0.7.4
    - pillow==5.1.0
    - prompt-toolkit==1.0.15
    - protobuf==3.6.0
    - pygments==2.2.0
    - pymongo==3.6.1
    - pyparsing==2.2.0
    - python-dateutil==2.7.3
    - pytz==2018.4
    - pywavelets==0.5.2
    - pywinpty==0.5.5
    - pyyaml==3.13
    - pyzmq==17.0.0
    - qtconsole==4.3.1
    - requests==2.20.1
    - retrying==1.3.3
    - scikit-image==0.14.2
    - scikit-learn==0.19.1
    - scipy==1.1.0
    - seaborn==0.9.0
    - send2trash==1.5.0
    - simplegeneric==0.8.1
    - six==1.11.0
    - sknw==0.13
    - tensorflow-gpu==1.13.1
    - termcolor==1.1.0
    - terminado==0.8.1
    - testpath==0.3.1
    - toolz==0.9.0
    - tornado==5.0.2
    - tqdm==4.23.4
    - traitlets==4.3.2
    - urllib3==1.24.1
    - wcwidth==0.1.7
    - webencodings==0.5.1
    - werkzeug==0.14.1
    - widgetsnbextension==3.2.1
    - win-unicode-console==0.5
